import io::*;
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module dokifive_p50_top(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,

	//////////// Arduino //////////
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N
);



	//=======================================================
	//  REG/WIRE declarations
	//=======================================================

	GPREGS_T GPREGS;
	assign HEX0 = { 1'b1, GPREGS.GPR1 };
	assign HEX1 = { 1'b1, GPREGS.GPR1 >> 4};
	assign HEX2 = { 1'b1, GPREGS.GPR1 >> 8};
	assign HEX3 = { 1'b1, GPREGS.GPR1 >> 12};
	assign HEX4 = { 1'b1, GPREGS.GPR1 >> 16};
	assign HEX5 = { 1'b1, GPREGS.GPR1 >> 20};

	//=======================================================
	//  Structural coding
	//=======================================================
	dokifive_soc #(
	.INITIAL_MOCK_INSTR("instr_init.mem")
	) dokifive_soc_instance (
		.clk(ADC_CLK_10),
		.rst(~KEY[0]),
		.GPREGS(GPREGS)
	);



endmodule
